### ISSUE TITLE
Mexican food little things.

### ISSUE THREAD

**Issue by Glunkussss** [McKleans-Scripts/mk-items#9]
![meat](https://user-images.githubusercontent.com/102635797/178831014-8b6e067a-4312-4727-9f92-ffb211b34f60.png)
![taco](https://user-images.githubusercontent.com/102635797/178831016-86ab1647-298f-4264-bb2e-b4d40d7ab160.png)
![bun](https://user-images.githubusercontent.com/102635797/178831018-1f07d6a7-86b2-4f36-a524-58a0c1e43c7c.png)
![lettuce](https://user-images.githubusercontent.com/102635797/178831021-da5fb6a7-3d69-4d1c-92ed-49174851d5c3.png)

**Comment by McKlean** [comment]
Thanks man, they will be in the next push
